# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sundpood.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#background{\n"
"    background:rgb(48, 48, 48);\n"
"}\n"
"\n"
"QWidget{\n"
"    background: rgb(44, 44, 44);    \n"
"    font: 25 14pt \"Calibri Light\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: rgb(58, 58, 58);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(53, 53, 53);\n"
"}\n"
"\n"
"QListWidget{\n"
"    margin: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item[Custom=\"true\"]{\n"
"    background: rgb(48, 48, 48);\n"
"}\n"
"\n"
"QListWidget::item:hover{\n"
"    background:  rgb(53, 53, 53);\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background: rgb(48, 48, 48);\n"
"    color: black;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    border: 1px transparent rgb(58, 58, 58);\n"
"    border-radius: 4px;\n"
"    background: rgb(48, 48, 48);\n"
"    width: 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical{\n"
"    background: rgb(48, 48, 48);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical{\n"
"    background: rgb(48, 48, 48);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(0, 70, 171, 41))
        self.play_button.setStyleSheet("")
        self.play_button.setFlat(False)
        self.play_button.setObjectName("play_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(0, 120, 171, 41))
        self.stop_button.setStyleSheet("")
        self.stop_button.setDefault(False)
        self.stop_button.setFlat(False)
        self.stop_button.setObjectName("stop_button")
        self.select_label = QtWidgets.QLabel(self.centralwidget)
        self.select_label.setGeometry(QtCore.QRect(0, 30, 641, 31))
        self.select_label.setStyleSheet("background:black;\n"
"color: white;")
        self.select_label.setText("")
        self.select_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_label.setObjectName("select_label")
        self.hkset = QtWidgets.QPushButton(self.centralwidget)
        self.hkset.setGeometry(QtCore.QRect(0, 190, 171, 41))
        self.hkset.setObjectName("hkset")
        self.catList = QtWidgets.QListWidget(self.centralwidget)
        self.catList.setGeometry(QtCore.QRect(10, 270, 151, 201))
        self.catList.setStyleSheet("QListWidget::item{\n"
"    padding: 6px;\n"
"}")
        self.catList.setObjectName("catList")
        self.soundList = QtWidgets.QListWidget(self.centralwidget)
        self.soundList.setGeometry(QtCore.QRect(170, 60, 471, 421))
        self.soundList.setObjectName("soundList")
        self.pref_button = QtWidgets.QPushButton(self.centralwidget)
        self.pref_button.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.pref_button.setStyleSheet("QPushButton{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background: rgba(194, 213, 254, 128);\n"
"}")
        self.pref_button.setObjectName("pref_button")
        self.hotkeys_button = QtWidgets.QPushButton(self.centralwidget)
        self.hotkeys_button.setGeometry(QtCore.QRect(110, 0, 111, 31))
        self.hotkeys_button.setStyleSheet("QPushButton{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background: rgba(194, 213, 254, 128);\n"
"}")
        self.hotkeys_button.setObjectName("hotkeys_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(600, 0, 41, 31))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background: rgba(254, 119, 122, 128);\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.min_button = QtWidgets.QPushButton(self.centralwidget)
        self.min_button.setGeometry(QtCore.QRect(560, 0, 41, 31))
        self.min_button.setStyleSheet("QPushButton{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background: rgba(194, 213, 254, 128);\n"
"}")
        self.min_button.setObjectName("min_button")
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -10, 641, 491))
        self.background.setStyleSheet("")
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(self.background)
        self.label.setGeometry(QtCore.QRect(10, 250, 151, 21))
        self.label.setStyleSheet("background: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.background.raise_()
        self.play_button.raise_()
        self.stop_button.raise_()
        self.select_label.raise_()
        self.hkset.raise_()
        self.catList.raise_()
        self.soundList.raise_()
        self.pref_button.raise_()
        self.hotkeys_button.raise_()
        self.exit_button.raise_()
        self.min_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sundpood"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.hkset.setText(_translate("MainWindow", "Set Hotkey"))
        self.pref_button.setText(_translate("MainWindow", "Settings"))
        self.hotkeys_button.setText(_translate("MainWindow", "Hotkeys"))
        self.exit_button.setText(_translate("MainWindow", "X"))
        self.min_button.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Categories"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
