# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(420, 500))
        MainWindow.setMaximumSize(QtCore.QSize(420, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: rgb(44, 44, 44);    \n"
"    font: 25 14pt \"Calibri Light\";\n"
"}\n"
"\n"
"QLabel{\n"
"    background: none\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: rgb(58, 58, 58);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(53, 53, 53);\n"
"}\n"
"\n"
"QListWidget{\n"
"    margin: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item[Custom=\"true\"]{\n"
"    background: rgb(48, 48, 48);\n"
"}\n"
"\n"
"QListWidget::item:hover{\n"
"    background:  rgb(53, 53, 53);\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background: rgb(48, 48, 48);\n"
"    color: black;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    border: 1px transparent rgb(58, 58, 58);\n"
"    border-radius: 4px;\n"
"    background: rgb(48, 48, 48);\n"
"    width: 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background: rgb(48, 48, 48);\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical{\n"
"    background: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical{\n"
"    background: rgb(58, 58, 58);\n"
"}\n"
"\n"
"#background{\n"
"    background:rgb(48, 48, 48);\n"
"}\n"
"\n"
"#exit_button{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"#exit_button:hover{\n"
"    color: black;\n"
"    background: rgba(254, 119, 122, 128);\n"
"}\n"
"\n"
"#min_button{\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"#min_button:hover{\n"
"    color: black;\n"
"    background: rgba(194, 213, 254, 128);\n"
"}\n"
"\n"
"#update_button:hover{\n"
"    background:rgba(10, 128, 179, 128);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(380, 0, 41, 31))
        self.exit_button.setStyleSheet("")
        self.exit_button.setObjectName("exit_button")
        self.min_button = QtWidgets.QPushButton(self.centralwidget)
        self.min_button.setGeometry(QtCore.QRect(340, 0, 41, 31))
        self.min_button.setStyleSheet("")
        self.min_button.setObjectName("min_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 391, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pref_over = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over.setStyleSheet("background:none")
        self.pref_over.setObjectName("pref_over")
        self.gridLayout.addWidget(self.pref_over, 0, 0, 1, 1)
        self.pref_over_el5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el5.setObjectName("pref_over_el5")
        self.gridLayout.addWidget(self.pref_over_el5, 5, 0, 1, 1)
        self.pref_over_el2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el2.setObjectName("pref_over_el2")
        self.gridLayout.addWidget(self.pref_over_el2, 2, 0, 1, 1)
        self.select_move_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_down.setObjectName("select_move_down")
        self.gridLayout.addWidget(self.select_move_down, 2, 1, 1, 1)
        self.select_move_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_right.setObjectName("select_move_right")
        self.gridLayout.addWidget(self.select_move_right, 4, 1, 1, 1)
        self.select_move_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_up.setObjectName("select_move_up")
        self.gridLayout.addWidget(self.select_move_up, 1, 1, 1, 1)
        self.pref_over_el3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el3.setObjectName("pref_over_el3")
        self.gridLayout.addWidget(self.pref_over_el3, 3, 0, 1, 1)
        self.stop_sound = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_sound.setObjectName("stop_sound")
        self.gridLayout.addWidget(self.stop_sound, 6, 1, 1, 1)
        self.pref_over_el6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el6.setObjectName("pref_over_el6")
        self.gridLayout.addWidget(self.pref_over_el6, 6, 0, 1, 1)
        self.pref_over_el4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el4.setObjectName("pref_over_el4")
        self.gridLayout.addWidget(self.pref_over_el4, 4, 0, 1, 1)
        self.select_move_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_left.setObjectName("select_move_left")
        self.gridLayout.addWidget(self.select_move_left, 3, 1, 1, 1)
        self.pref_over_el1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el1.setObjectName("pref_over_el1")
        self.gridLayout.addWidget(self.pref_over_el1, 1, 0, 1, 1)
        self.play_sound = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.play_sound.setObjectName("play_sound")
        self.gridLayout.addWidget(self.play_sound, 5, 1, 1, 1)
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 421, 71))
        self.background.setStyleSheet("")
        self.background.setObjectName("background")
        self.title = QtWidgets.QLabel(self.background)
        self.title.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.pref_themes = QtWidgets.QLabel(self.centralwidget)
        self.pref_themes.setGeometry(QtCore.QRect(10, 290, 201, 31))
        self.pref_themes.setObjectName("pref_themes")
        self.themesList = QtWidgets.QListWidget(self.centralwidget)
        self.themesList.setGeometry(QtCore.QRect(10, 330, 401, 161))
        self.themesList.setObjectName("themesList")
        self.background.raise_()
        self.exit_button.raise_()
        self.min_button.raise_()
        self.gridLayoutWidget.raise_()
        self.pref_themes.raise_()
        self.themesList.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preferences"))
        self.exit_button.setText(_translate("MainWindow", "X"))
        self.min_button.setText(_translate("MainWindow", "-"))
        self.pref_over.setText(_translate("MainWindow", "Overlay control"))
        self.pref_over_el5.setText(_translate("MainWindow", "Overlay play sound"))
        self.pref_over_el2.setText(_translate("MainWindow", "Overlay menu down"))
        self.select_move_down.setText(_translate("MainWindow", "PushButton"))
        self.select_move_right.setText(_translate("MainWindow", "PushButton"))
        self.select_move_up.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el3.setText(_translate("MainWindow", "Overlay menu left"))
        self.stop_sound.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el6.setText(_translate("MainWindow", "Overlay stop sound"))
        self.pref_over_el4.setText(_translate("MainWindow", "Overlay menu right"))
        self.select_move_left.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el1.setText(_translate("MainWindow", "Overlay menu up"))
        self.play_sound.setText(_translate("MainWindow", "PushButton"))
        self.title.setText(_translate("MainWindow", "Preferences"))
        self.pref_themes.setText(_translate("MainWindow", "Themes"))
